### ISSUE TITLE
Group select causes other elements to shift.

### ISSUE THREAD

**Issue by jhundley9109** [EffEPi/fabric.curvedText#23] opened 2015-10-16 18:00 UTC
See http://jsfiddle.net/jhundley9109/z7dw9ekn/

By simply selecting all the elements on the canvas, some, actually all elements except one shifts. When clicking off the the group select the elements go back to place. The item that does not shift seems to be based on the index of the item in the canvas.getActiveObjects() array. This is why I put a obj.bringToFront() in the fiddle.

**Comment by Jochuaf** [comment] 2015-10-25 11:00
Hi Effepi,
Your code works really great except for grouping as mentioned by jhundley9109. Plus, rotation mess up after 2 tries.
Is there any solution for this problem?
Thanks in advance.
ps: I mixed up 2 conversations and answered #20 by mistake.

**Comment by jhundley9109** [comment] 2016-02-19 17:52
I have figured out the cause of this issue. During the render function, the ctx.save() and ctx.restore() are commented out. These need to be uncommented. Also, the line with the this.clipTo&&ctx.restore() probably needs modified.

**Comment by EffEPi** [comment] 2016-05-16 15:49
Can you test it again and maybe create a pull request for it?

**Comment by EffEPi** [comment] 2016-05-16 16:20
I believe that the problem is fixed with the latest merge

**Closed by EffEPi** 2016-05-16 16:20 UTC
